### ISSUE TITLE
What is documentation?

### ISSUE THREAD

**Issue by qxtony** [LeeeeT/valtypes#28]
Good afternoon! My name is Anton.

I have been using your library for a year. I really like using this library. I have been studying the source code of your library for a long time. What I just didn't see there! But that's not what I wanted to tell you at all.

And so, do you know why, I studied your source code? The fact is that there is no documentation in the repository. It is **completely** absent. And so, a counter question is asked: How to use your library without knowing its functionality?

Turning to the developers of this miracle, I ask you to add documentation. Preferably, to everything that can be used in practice. Also, it does not hurt to add examples of use in everyday tasks. If the developer does not add documentation, then I will remove the star from his repository. You are given **1** day. Time has passed.

Sincerely, qxtony.

**Comment by LeeeeT** [comment]
Hi, qxtony! I appreciate your concern. Unfortunately, the project is still a work in progress. Documentation is coming soon. Please be patient. 😊

**Comment by qxtony** [comment]
Thanks for the answer!
